config/routes.rb
Jam::Application.routes.draw do
  resources :events do
    resources :comments
    resources :attendances
    resources :submissions do
      resources :votes
      resources :comments
    end
  end

  devise_for :users

  root :to => "events#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user
      can :manage, Event, :organizer_id => user.id
      can :manage, Attendance, :attendant_id => user.id
      can :manage, Submission, :author_id => user.id
      can :manage, Vote do |vote|
        vote.user == user && user.events_attended.include?(vote.submission.event)
      end
      can :manage, Comment, :author_id => user.id
    end
  end
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :attendant, :class_name => "User"
  belongs_to :event

  validates_presence_of :attendant, :event
  validates_uniqueness_of :attendant_id, :scope => :event_id

  attr_protected :attendant, :event
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, :class_name => "User"
  belongs_to :commentable, :polymorphic => true

  validates_presence_of :author, :body
end

app/models/event.rb
require 'textilized_attributes'

class Event < ActiveRecord::Base
  include TextilizedAttributes

  belongs_to :organizer, :class_name => "User"
  has_many :attendances
  has_many :attendants, :through => :attendances
  has_many :submissions
  has_many :comments, :as => :commentable

  validates_presence_of :title, :description, :organizer

  scope :past, lambda { where('starting_at < ?', Time.now) }
  scope :future, lambda { where('starting_at >= ? OR starting_at IS NULL', Time.now) }

  attr_protected :organizer

  after_create :attend_by_organizer
  before_destroy :remove_organizer

  textilized_attrs :description

  def organized_by?(user)
    self.organizer == user
  end

  def attended_by?(user)
    self.attendants.include? user
  end

  def attendance_for(user)
    self.attendances.find_by_attendant_id(user.id)
  end

  protected
  def attend_by_organizer
    self.attendants << self.organizer
  end

  def remove_organizer
    self.attendants.delete(self.organizer)
  end
end

app/models/submission.rb
require 'textilized_attributes'

class Submission < ActiveRecord::Base
  include TextilizedAttributes

  belongs_to :author, :class_name => "User"
  belongs_to :event
  has_many :votes
  has_many :users_voted, :through => :votes, :source => :user
  has_many :comments, :as => :commentable

  validates_presence_of :event, :author, :title

  attr_protected :author, :event
  
  textilized_attrs :description

  def authored_by?(user)
    self.author == user
  end

  def voted_by?(user)
    self.users_voted.include? user
  end

  def vote_for(user)
    self.votes.find_by_user_id(user.id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events_organized, :class_name => "Event", :foreign_key => "organizer_id"
  has_many :attendances, :foreign_key => "attendant_id"
  has_many :events_attended, :through => :attendances, :source => :event
  has_many :submissions, :foreign_key => "author_id"
  has_many :votes
  has_many :submissions_voted, :through => :votes, :source => :submission

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  validates :name, :presence => true, :uniqueness => true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :submission

  validates_presence_of :user, :submission
  validates_uniqueness_of :user_id, :scope => :submission_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :setup_event
  load_and_authorize_resource

  respond_to :html
  
  def new
    respond_with(@attendance)
  end
  
  def create
    @attendance.event_id, @attendance.attendant = params[:event_id], current_user
    @attendance.save
    respond_with(@attendance,  :location => event_url(@event))
  end

  def destroy
    @attendance.destroy
    respond_with(@attendance,  :location => event_url(@event))
  end

  protected
  def setup_event
    @event = Event.find(params[:event_id]) if params[:event_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :setup_commentable, :except => :destroy
  load_and_authorize_resource

  respond_to :html

  def new
    @comment.commentable = @commentable
    respond_with(@comment)
  end

  def create
    @comment.commentable, @comment.author = @commentable, current_user
    @comment.save
    respond_with(@comment, :location => polymorphic_url([@event, @submission]))
  end

  def destroy
    @comment.destroy
    respond_with(@comment, :location => polymorphic_url([@event, @submission]))
  end

  protected
  def setup_commentable
    @event = Event.find(params[:event_id]) if params[:event_id]
    @submission = Submission.find(params[:submission_id]) if params[:submission_id]
    @commentable = @submission || @event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource

  before_filter :set_meta_tags

  respond_to :html

  def index
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event.organizer = current_user
    @event.save
    respond_with(@event, :location => events_url)
  end

  def update
    @event.update_attributes(params[:event])
    respond_with(@event, :location => events_url)
  end

  def destroy
    @event.destroy
    respond_with(@event, :location => events_url)
  end

  protected
  def set_meta_tags
   if @event
     @meta_title = @event.title
     @meta_description = @event.description
   end
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  respond_to :html

  def index
    @event = Event.find(params[:event_id])
    respond_with(@submissions)
  end

  def show
    respond_with(@submission)
  end

  def new
    respond_with(@submission)
  end

  def edit
  end

  def create
    @submission.author, @submission.event_id = current_user, params[:event_id]
    @submission.save
    respond_with(@submission, :location => event_url(@submission.event))
  end

  def update
    @submission.update_attributes(params[:submission])
    respond_with(@submission, :location => event_url(@submission.event))
  end

  def destroy
    @submission.destroy
    respond_with(@submission, :location => event_url(@submission.event))
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :except => :create

  respond_to :html
  
  def create
    @event = Event.find(params[:event_id])
    @vote = Vote.new(params[:vote])
    @vote.submission_id, @vote.user = params[:submission_id], current_user
    authorize! :create, @vote
    @vote.save
    respond_with(@vote, :location => event_url(@event))
  end

  def destroy
    @event = Event.find(params[:event_id])
    @vote.destroy
    respond_with(@vote, :location => event_url(@event))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def localized(date, options = {})
    I18n.l(date, options) if date
    date
  end

  def meta_title
    @meta_title || I18n.t('site.title')
  end

  def meta_description
    @meta_description || I18n.t('site.description')
  end
end

app/views/attendances/_form.html.haml
= simple_form_for([:event, @attendance]) do |f|
  - if @attendance.errors.any?
    #error_explanation
      %h2
        = pluralize(@attendance.errors.count, "error")
        prohibited this event from being saved:

      %ul
      - @attendance.errors.full_messages.each do |msg|
        %li= msg

  .inputs
    = f.input :comment

  .actions
    = f.button :submit

app/views/attendances/new.html.haml
%h2= "Attendance to #{@event.title}"

= render 'form'

app/views/comments/_comment.html.haml
%dt
  %strong= comment.author.name
%dd
  = comment.body
  %br
  = I18n.l(comment.created_at, :format => :short)

app/views/comments/_form.html.haml
= simple_form_for([@event, @submission, @comment]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this event from being saved:

      %ul
      - @comment.errors.full_messages.each do |msg|
        %li= msg

  .inputs
    = f.input :body

  .actions
    = f.button :submit

app/views/comments/new.html.haml
%h2= "Comment"

= render 'form'

app/views/events/_event.html.haml
%li.event
  %h3= link_to event.title, event
  %p
    = I18n.l(event.starting_at, :format => :event) if event.starting_at
    - unless event.place.blank? 
      at 
      %strong= event.place
    organized by
    %strong= event.organizer.name
  %p
    = event.textilized_description
  .actions
    = link_to 'comments', "#{event_path(event)}#comments"
    = "(#{event.comments.size})"
    \/
    = link_to 'submissions', "#{event_path(event)}#submissions"
    = "(#{event.submissions.size})"
    \/
    = link_to 'attendants', "#{event_path(event)}#attendants"
    = "(#{event.attendants.size})"
    - if can? :manage, event
      .organizer-actions
        = link_to 'edit', edit_event_path(event)
        \/
        = link_to 'destroy', event, :confirm => 'Are you sure?', :method => :delete

app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h3
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:

      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .inputs
    = f.input :starting_at, :include_blank => true
    = f.input :description
    = f.input :title
    = f.input :place

  .actions
    = f.button :submit

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
- unless @events.future.size.zero?
  %h2 Incoming events
  %ul
    - @events.future.each do |event|
      = render :partial => "event", :locals => {:event => event}

- unless @events.past.size.zero?
  %h2 Past events
  %ul
    - @events.past.each do |event|
      = render :partial => "event", :locals => {:event => event}

= content_for :user_actions do
  = link_to 'new event', new_event_path

app/views/events/new.html.haml
%h2 New event

= render 'form'

app/views/events/show.html.haml
%h2= @event.title

.event
  .description
    %p
      = @event.textilized_description
  .info  
    %dl
      %dt Starting at:
      %dd= @event.starting_at ? I18n.l(@event.starting_at, :format => :event) : "yet unknown"
      %dt Place:
      %dd= @event.place.present?? @event.place : "yet unknown"
      %dt Organizer:
      %dd
        = @event.organizer.name
        = "(#{mail_to @event.organizer.email})".html_safe

%h3 Attendants
%ul#attendants
  - @event.attendances.each do |attendance|
    %li
      = attendance.attendant.name
      = "(#{attendance.comment})" unless attendance.comment.blank?

%h3 Submissions
%ul#submissions
  - @event.submissions.each do |submission|
    %li.submission
      %h4= link_to submission.title, [submission.event, submission]
      %div.footer
        submitted by
        %strong= submission.author.name
        %span.right
          = "#{submission.votes.size} likes"
      .actions
        - unless submission.voted_by? current_user
          = link_to 'like', event_submission_votes_path(submission.event, submission), :class => 'vote-up', :method => :post, :"data-user_id" => current_user.id, :"data-submission_id" => submission.id
        - else
          = link_to 'unlike', [submission.event, submission, submission.vote_for(current_user)], :method => :delete
        .author-actions
          - if submission.authored_by? current_user
            = link_to 'edit', edit_event_submission_path(submission.event, submission)
            \/
            = link_to 'destroy', [submission.event, submission], :confirm => 'Are you sure?', :method => :delete

%h3 Comments
%dl#comments
  - @event.comments.each do |comment|
    = render :partial => 'comments/comment', :locals => {:comment => comment}

.actions
  = link_to 'comment', new_event_comment_path(@event)

= content_for :user_actions do
  = link_to 'new submission', new_event_submission_path(@event)
  - unless @event.attendants.include? current_user
    \/
    = link_to 'attend', new_event_attendance_path(@event)
  - else
    - unless @event.organized_by? current_user
      \/
      = link_to 'quit', event_attendance_path(@event, @event.attendance_for(current_user)), :method => :delete

app/views/layouts/_user.html.haml
- if current_user
  %strong= current_user.name
  = link_to "(sign out)", destroy_user_session_path
  %ul
    %li= "submissions (#{current_user.submissions.size})"
    %li= "votes (#{current_user.votes.size})"
  = yield :user_actions
- else
  = link_to "sign in", new_user_session_path
  or
  = link_to "register", new_user_registration_path
  

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    %title= meta_title
    %meta{:name => :description, :content => meta_description}
  %body
    %div#container
      %header
        = link_to root_url, :class => 'logo' do
          %h1.title
            = "DRUG Jam!"
        %h2.subtitle
          = "happy hacking"
        %p.notice
          = notice
        %p.alert
          = alert
        %div.user
          = render :partial => "layouts/user"
      %div#content
        %section#body
          = yield

app/views/submissions/_form.html.haml
= simple_form_for([:event, @submission]) do |f|
  - if @submission.errors.any?
    #error_explanation
      %h2
        = pluralize(@submission.errors.count, "error")
        prohibited this submission from being saved:

      %ul
      - @submission.errors.full_messages.each do |msg|
        %li= msg

  .inputs
    = f.input :title
    = f.input :description

  .actions
    = f.button :submit

app/views/submissions/edit.html.haml
%h1 Editing submission

= render 'form'

= link_to 'Show', [@submission.event, @submission]
\|
= link_to 'Back', event_submissions_path(@submission.event)

app/views/submissions/index.html.haml
%h1 Listing submissions

%table
  %tr
    %th Author
    %th Event
    %th Title
    %th Description
    %th
    %th
    %th
    %th
    %th

  - @submissions.each do |submission|
    %tr
      %td= submission.author
      %td= submission.event
      %td= submission.title
      %td= submission.description
      %td= link_to 'Show', [submission.event, submission]
      - if submission.authored_by? current_user
        %td= link_to 'Edit', edit_event_submission_path(submission.event, submission)
        %td= link_to 'Destroy', [submission.event, submission], :confirm => 'Are you sure?', :method => :delete

      - unless submission.voted_by? current_user
        %td= link_to 'Vote up', event_submission_votes_path(submission.event, submission), :class => 'vote-up', :method => :post, :"data-user_id" => current_user.id, :"data-submission_id" => submission.id
      - else
        %td= link_to 'Vote down', [submission.event, submission, submission.vote_for(current_user)], :method => :delete


%br

= link_to 'New Submission', new_event_submission_path(@event)

app/views/submissions/new.html.haml
%h2 New submission

= render 'form'

app/views/submissions/show.html.haml
%h2= @submission.title

.submission
  .description
    %p
      = @submission.textilized_description
  .info  
    %dl
      %dt Author:
      %dd= @submission.author.name 
      %dt Liked by:
      %dd 
        %ul
          - @submission.users_voted.each do |user|
            %li= user.name
            
%h3 Comments
%dl#comments
  - @submission.comments.each do |comment|
    = render :partial => 'comments/comment', :locals => {:comment => comment}

.actions
  = link_to 'comment', new_event_submission_comment_path(@submission.event, @submission)

= content_for :user_actions do
  - if can? :manage, @submission
    = link_to 'edit', edit_event_submission_path(@submission.event, @submission)